theme: minima
title: Lord Commander's Ramblings
author: Yuki Fuyuki
description: A collection of ramblings from the Lord Commander regarding how the FC is run
twitter_username: yukifuyuki
github_username: yukifuyuki